### ISSUE TITLE
Running on MNIST

### ISSUE THREAD

**Issue by govinda-kamath** [ravidziv/IDNNs#10]
Hi,

I was trying to run this on the MNIST data-set, but setting `-d_name MNIST` does not seem to work.  What's the right parameter I must pass in?

**Comment by liuzqt** [comment]
Having the same problem here.....it seems that we need to modify other parameter to run on MNIST

**Comment by gladiator8072** [comment]
hello, based on MNIST, i found the non-linear function is using relu while the range of bins is [-1,1]
it looks such range is applying on tanh?

**Comment by pmorerio** [comment]
@gladiator8072  I was thinking the same. I opened [an issue](https://github.com/ravidziv/IDNNs/issues/12) for that.

**Comment by ravidziv** [comment]
Hi,

 the code doesn't support to estimate the mutual information in MNIST with ReLU activation.  You can find several papers that try to do it. For example [this](https://arxiv.org/abs/1806.00400) one.
