### ISSUE TITLE
[BUG] Calculate Information for Epoch

### ISSUE THREAD

**Issue by ATriantafyllopoulos** [ravidziv/IDNNs#16]
Hi, there's a typo in line 143 of your information_process.py script:

`parmas = calc_by_sampling_neurons(ws_iter_index=ws_iter_index, num_of_samples=num_of_samples, label=label,
                                          sigma=sigma, bins=bins, pxs=pxs)`

`parmas` should be renamed to `params` since the latter is what the function returns

**Comment by ravidziv** [comment]
right, thanks!
