### ISSUE TITLE
"Calculating the information" takes a long time

### ISSUE THREAD

**Issue by pinouchon** [ravidziv/IDNNs#3]
Hi,

I am running the main script without any issues: `python main.py`

The part of the script that trains the network takes about a minute (after output `Start running the network`)

The part that calculates the information takes a very long time (after output `Start calculating the information...`). Something like 5 to 10 minutes for every 30 epochs. So the whole script will take about 5 hours to complete. I have tried on both a MacBookPro with an i7, and a more beefy machine with a ryzen 7 (both have the speed I reported above). Note that all my CPUs are at 100% during this part, so I suppose parallelisation is already done, or wont help...
My main issue with it is that it will make experimenting with it slow, as I have to wait a long time to see the results after each modification.

Is this the expected behavior ? Is it the same speed on your machine ?
Can I do anything to speed it up ?

Thanks in advance

**Comment by ravidziv** [comment]
Try to take the last commit, It should be faster know. 
Indeed the MI calculation takes more time, but at least on my computer (Mac Pro) it takes  now around 1 second for 1 epoch
