### ISSUE TITLE
Unable to clone with eCryptfs

### ISSUE THREAD

**Issue by bdwyer2** [ravidziv/IDNNs#5]
The eCryptfs file system does not support file names longer than 143 characters such as the files in the `jobs/` directory. This makes it impossible for me to clone this repository on my machine.

Would it be possible to shorten some of the directory names in the `jobs/` directory? I'm sure other linux users will face this issue as well. Thanks!

**Comment by ravidziv** [comment]
Done!

**Comment by bdwyer2** [comment]
That was fast!!!! Thanks!

Resolved via b04bc4d0f9949a503f9f7250e375537aa154ef17
